### ISSUE TITLE
Delivery entity required

### ISSUE THREAD

**Issue by belosh59** [BogdanParashchak/GoodsPartner#125]
**Delivery**
1. В Базі створити ентіті Delivery. В неї має бути своя унікальна UUID, дата і список ордерів, маршрут і завантаження
1. Create entity Delivery. It should have following fields:
```
 id: UUID
 date: LocalDate
 orders: List<OrderExternal> -- List of orders which have 
 routes: List<Route>
 carLoad: List<CarLoad>
```

Api Delivery:
- GET /delivery (pagable + filtering by date + by default return in descending order)- return List of DeliveryDto with all of the necessary information 
- GET /delivery/{uuid} - return requested DeliveryDto
- POST /delivery - create Delivery entity by date with DRAFT status
- PUT /delivery/{uuid} - update accept DeliveryDto body and update status

**Orders**
1. Додати поле delivery яке буде ссилатися на ентіті Delivery по даті створення

**Route**
1. Add field delivery with reference to Delivery entity (table)

**CarLoading**
1. Create separate endpoint to retrieve carLoading information for specific Delivery Id. That shouls retrieve from DB list of orders with the assigned cars and group that information by cars in first view and by productName in second view.

**Flow**:
1. When the user reviewed \ validated \ refreshed orders from 1C he click generate Delivery
3. On the backend
   2.1. (POST) In database we create entity "Delivery"
   2.2 (POST) We load again orders from 1C and save them into DB with reference field delivery being updated
   2.3 (POST) Generate Route for given delivery. As the result we are saving list of Routes in DB with delivery reference. For cars which where calculated for list of Routes, Update underlying order in respective RoutePoints to be linked to specific cars
  2.4 (GET) Get car loading information that is already available 

4. While the route is in draft we could change Delivery if needed. Which could be 3 different actions: 
    Recalculate Route \ Refresh Orders + Recalculate Route \ Delete delivery
    When the Route moved into `In Progress` and has been started we could not change it anymore
    
5. While the route is not `InProgress` we have the asnyc process which is matching if Orders list is in sync with external system (1C)

**Comment by BogdanParashchak** [comment]
https://github.com/BogdanParashchak/GoodsPartner/wiki/Delivery
