### ISSUE TITLE
Add endpoint to persist list off accepted orders from FE

### ISSUE THREAD

**Issue by belosh59** [BogdanParashchak/GoodsPartner#150]
When the user fixed all of the necessary Addresses and added required Order related information, he clicks generate Delivery.
Which by fact need save the snapshot of all the orders into DB

Freeze flag and delivery duration should be added sent as well if present

TODO:
Add  POST: /api/v1/orders to order endpoint, which accept list of OrderDto with necessary information.
Save all orders and as the side effect save the new accepted autoparsed addresses or fixed addresses

**Comment by BogdanParashchak** [comment]
TODO: 
in OrderDto add fields:

- boolean isFrozen
- LocalDateTime deliveryRangeStart
- LocalDateTime deliveryRangeEnd
