### ISSUE TITLE
[Backend/Bug] Check for car loading algorithm

### ISSUE THREAD

**Issue by BogdanParashchak** [BogdanParashchak/GoodsPartner#61]
![image](https://user-images.githubusercontent.com/86907923/184931278-eb6fe820-43ae-49d4-8fb0-b5c36ddfe895.png)
![image](https://user-images.githubusercontent.com/86907923/184931679-f279ff8d-fba3-4b57-9c9a-341d30f4d84e.png)

**Comment by BogdanParashchak** [comment]
18/02/2022

**Comment by 0ffffh** [comment]
![Image](https://user-images.githubusercontent.com/1705653/185500361-8efb611b-617c-412b-bf63-e086d0b2f40e.png)
![Image](https://user-images.githubusercontent.com/1705653/185500364-78490e96-df33-4d7b-bc67-b9ba437dfd2f.png)
![Image](https://user-images.githubusercontent.com/1705653/185500363-347ba03f-3301-4dc0-a743-3186041ce77e.png)
![Image](https://user-images.githubusercontent.com/1705653/185500362-d0c6a529-345b-4797-8e7b-c73e84628404.png)
