### ISSUE TITLE
Отчет+вью загрузки по артикулу (с привязкой к машинам)

### ISSUE THREAD

**Issue by BogdanParashchak** [BogdanParashchak/GoodsPartner#68]
Группировка заказов по товарам (раскладка про которую говорил Дима) Я бы делал и так как у нас есть сейчас (с расчетом на порядок загрузки машины) и так как сказал Дима. Когда просто грузим все в нужном количестве. Мы же не только для Димы делаем. Зачем удалять функционал. А он может быть полезен и внутри проекта Димы. В Экселе мы вообще можем сделать вторую вкладку. НА первой то что хочет Дима, на второй то как мы сделали.

**Comment by Ishei5** [comment]
Пример:

[\[2022-08-29_11-11-31\]Завантаження_машин_на_2022-07-12.xlsx](https://github.com/BogdanParashchak/GoodsPartner/files/9442810/2022-08-29_11-11-31._._._2022-07-12.xlsx)
