### ISSUE TITLE
Coordination with Dima displaying of units for measure of goods (kilogram, liter, etc.) 

### ISSUE THREAD

**Issue by BogdanParashchak** [BogdanParashchak/GoodsPartner#73]
Можно в форме письма или сообщения в телеграм - не дожидаясь колла. Относится к задаче "высчитывание веса (объема) товара для погрузки.

**Comment by BogdanParashchak** [comment]
процесинг різних одиниць вимірювання продукції і розрахунку фінальної маси

**Comment by hubarievanatali** [comment]
1.	Якщо відомий об'єм
Виходячи з того, що в середньому 1м3 це 200 кг (на основі аналізу транспортних перевізників), 1м=100 см, 1м3=100*100*100=1000000. Тоді 1000000/200=5000.
Отже для перерахунку об'єму у вагу для прорахунку завантаження авто використовуємо формулу:
Ширина*глибина*висота/5000
2.	Якщо л
Враховуючи різні показники густин рідин, що перевозиться, рахуємо, що:
1 л= 1,2 кг.
