### ISSUE TITLE
Build route to return to the MainStore till specified time

### ISSUE THREAD

**Issue by belosh59** [BogdanParashchak/GoodsPartner#81]
At the moment we build route till the last **RoutePoint** in **Route**.
But in fact we need to get back to the **MainStore** always!!

Add the store as the last point to the Route planning.
Decrease limit for 1C data retrieval to 8 elements so far. So that in total. we still in boundaries of 10 RoutePoints for the Route

**Comment by Eugene7011** [comment]
Отрисовать на фронте отрезок по возвращению на склад
