### ISSUE TITLE
1C load the Adress comment field and represent it for Order component

### ISSUE THREAD

**Issue by belosh59** [BogdanParashchak/GoodsPartner#86]
**BE:**
Load from 1C additional AddressComment field or any related to that information.
This informnation should be placed on Order Table for each order.
There user could specify timeranges or other Order valuable information (like phones, cash, freezer etc)

This about separate attributes for Route Constraints like time range or freezer

**FE:**
In case if comment larger then 100 symbols strip hower with fiull text

**Comment by Ishei5** [comment]
{
	"date": "2022-02-18",
	"validOrders": [
		{
			"id": 0,
			"refKey": "77d0df01-8e67-11ec-b3ce-00155dd72305",
			"orderNumber": "00000003703",
			"createdDate": "2022-02-15",
			"clientName": "Гранде дольче",
			"address": "вул. Кирилівська, 15/1.",
			"comment": "фіз обмін Ідеал-Групп ТОВ (Пікнік) ЗАБРАТИ Фісташкова паста (AY50ВС) 3 кг  ",
			"managerFullName": "Шевцова Галина                                    ",
			"products": [
				{
					"productName": "Фісташкова паста зелена 2х3 кг (AY50BD)",
					"amount": 1,
					"storeName": "Склад №1",
					"unitWeight": 3.0,
					"totalProductWeight": 3.0
				}
			],
			"orderWeight": 3.0,
			"validAddress": true
		},
		{
			"id": 0,
			"refKey": "b01d74e6-8fd3-11ec-b3ce-00155dd72305",
			"orderNumber": "00000003829",
			"createdDate": "2022-02-17",
			"clientName": "Кейк Продакшн (бн) Андрейчук К.Ю. ФОП",
			"address": "вул. Лисогірська, 4",
			"comment": "бн, тел. 096-451-43-73",
			"managerFullName": "Яна Седляр                                        ",
			"products": [
				{
					"productName": "Цукрова пудра (5 кг)",
					"amount": 6,
					"storeName": "Склад №1",
					"unitWeight": 5.0,
					"totalProductWeight": 30.0
				}
			],
			"orderWeight": 30.0,
			"validAddress": true
		},
		{
			"id": 0,
			"refKey": "53fb652b-8fd3-11ec-b3ce-00155dd72305",
			"orderNumber": "00000003825",
			"createdDate": "2022-02-17",
			"clientName": "Житня пекарня Хлібар  (Рігун Л.О ФОП 20,11,2020) ",
			"address": "вул. Межигірська 28",
			"comment": "бн ЗАМОРОЗКА КРУАСАНИ",
			"managerFullName": "Шевцова Галина                                    ",
			"products": [
				{
					"productName": "Мастер Джойа маргарин ( AG1GBB ) 1*20 кг",
					"amount": 1,
					"storeName": "Склад №1",
					"unitWeight": 20.0,
					"totalProductWeight": 20.0
				},
				{
					"productName": "Білий Сніг - посипка декораційна (1 кг)",
					"amount": 2,
					"storeName": "Склад №1",
					"unitWeight": 1.0,
					"totalProductWeight": 2.0
				},
				{
					"productName": "23555 Круасан класичний 70 г (шт)",
					"amount": 6,
					"storeName": "Склад №1",
					"unitWeight": 48.0,
					"totalProductWeight": 1.0
				}
			],
			"orderWeight": 23.0,
			"validAddress": true
		},
		{
			"id": 0,
			"refKey": "45da7002-8fd4-11ec-b3ce-00155dd72305",
			"orderNumber": "00000003831",
			"createdDate": "2022-02-17",
			"clientName": "Ідеал-Групп ТОВ (Пікнік)",
			"address": "вул. Кирилівська, 15/1",
			"comment": "бн + фіз обмін ",
			"managerFullName": "Шевцова Галина                                    ",
			"products": [
				{
					"productName": "Суміш хлібопекарська Гречаний Хліб, 10 кг",
					"amount": 2,
					"storeName": "Склад №1",
					"unitWeight": 10.0,
					"totalProductWeight": 20.0
				},
				{
					"productName": "AV88BB Орасі баріста мигдаль, мигдальний напій 6х1л",
					"amount": 2,
					"storeName": "Склад №1",
					"unitWeight": 6.0,
					"totalProductWeight": 12.0
				},
				{
					"productName": "AV88CB Орасі баріста кокос, напій кокосовий з рисом 6х1л",
					"amount": 2,
					"storeName": "Склад №1",
					"unitWeight": 6.0,
					"totalProductWeight": 12.0
				}
			],
			"orderWeight": 44.0,
			"validAddress": true
		},
		{
			"id": 0,
			"refKey": "f0b1befa-8fd2-11ec-b3ce-00155dd72305",
			"orderNumber": "00000003824",
			"createdDate": "2022-02-17",
			"clientName": "Орловська ФОП (нал)",
			"address": "вул. Північна, 3¶***/",
			"comment": "нал",
			"managerFullName": "Тетяна Кирильченко                                ",
			"products": [
				{
					"productName": "76304000 Чорнило Пьєзо EU/ME М 100 г",
					"amount": 1,
					"storeName": "Склад №1",
					"unitWeight": 1.0,
					"totalProductWeight": 1.0
				},
				{
					"productName": "76304001 Чорнило Пьєзо EU/ME Y 100 г",
					"amount": 1,
					"storeName": "Склад №1",
					"unitWeight": 1.0,
					"totalProductWeight": 1.0
				},
				{
					"productName": "76304002 Чорнило Пьєзо EU/ME C 100 г",
					"amount": 1,
					"storeName": "Склад №1",
					"unitWeight": 1.0,
					"totalProductWeight": 1.0
				},
				{
					"productName": "76304003 Чорнило Пьєзо EU/ME ВК 100 г",
					"amount": 1,
					"storeName": "Склад №1",
					"unitWeight": 1.0,
					"totalProductWeight": 1.0
				},
				{
					"productName": "7986 Підложка кругла золота/чорна D26 см, h-3мм (75 шт)",
					"amount": 1,
					"storeName": "Склад №1",
					"unitWeight": 75.0,
					"totalProductWeight": 1.0
				},
				{
					"productName": "10528 Листи для струйних малюнків-цукрові листи 50 шт. в уп.",
					"amount": 4,
					"storeName": "Склад №1",
					"unitWeight": 50.0,
					"totalProductWeight": 1.0
				},
				{
					"productName": "\"Срібний блиск\", банка 5г",
					"amount": 1,
					"storeName": "Склад №1",
					"unitWeight": 5.0,
					"totalProductWeight": 1.0
				}
			],
			"orderWeight": 7.0,
			"validAddress": true
		}
	],
	"invalidOrders": [
		{
			"id": 0,
			"refKey": "3103205d-8e5a-11ec-b3ce-00155dd72305",
			"orderNumber": "00000003669",
			"createdDate": "2022-02-15",
			"clientName": "ФУДКОМ ТОВ",
			"address": "м. Київ, вул. Архітектора Вербицького, 18",
			"comment": "бн. Вербицького ЗРАНКУ!!!!",
			"managerFullName": "Крамаренко Леся                                   ",
			"products": [
				{
					"productName": "Наповнювач фруктово-ягідний \"Білий\" (декоргель) (12 кг)",
					"amount": 1,
					"storeName": "Склад №1",
					"unitWeight": 12.0,
					"totalProductWeight": 12.0
				}
			],
			"orderWeight": 12.0,
			"validAddress": false
		},
		{
			"id": 0,
			"refKey": "d53c40d7-7906-11ec-b3ce-00155dd72305",
			"orderNumber": "00000001245",
			"createdDate": "2022-02-17",
			"clientName": "БУШЕ ТОВ (бн)",
			"address": "02081 м. Київ, вул. Здолбунівська, буд 3-А",
			"comment": "бн",
			"managerFullName": "Балашова Лариса                                   ",
			"products": [
				{
					"productName": "Глазур кондитерська біла (диски) (15 кг)",
					"amount": 1,
					"storeName": "Склад №1",
					"unitWeight": 15.0,
					"totalProductWeight": 15.0
				},
				{
					"productName": "Желатин харчовий (1 кг)",
					"amount": 4,
					"storeName": "Склад №1",
					"unitWeight": 1.0,
					"totalProductWeight": 4.0
				},
				{
					"productName": "Мастер Гурме 12х1л.(AV20TD)",
					"amount": 1,
					"storeName": "Склад №1",
					"unitWeight": 12.0,
					"totalProductWeight": 12.0
				},
				{
					"productName": "30301 Кондитерські мішки - гігієнічні  (шт)",
					"amount": 2,
					"storeName": "Склад №1",
					"unitWeight": 100.0,
					"totalProductWeight": 1.0
				}
			],
			"orderWeight": 32.0,
			"validAddress": false
		},
		{
			"id": 0,
			"refKey": "b01d74e5-8fd3-11ec-b3ce-00155dd72305",
			"orderNumber": "00000003828",
			"createdDate": "2022-02-17",
			"clientName": "Петрівка-Хорека ТОВ (бн)",
			"address": "вул. С. Бандери, 8, заїзд з вул. Вербова",
			"comment": "бн +ттн  /  тел +38 (067) 406-19-53 Зоя /ДОСТАВКА С 10 ДО 17/",
			"managerFullName": "Тетяна Кирильченко                                ",
			"products": [
				{
					"productName": "AV88BB Орасі баріста мигдаль, мигдальний напій 6х1л",
					"amount": 7,
					"storeName": "Склад №1",
					"unitWeight": 6.0,
					"totalProductWeight": 42.0
				},
				{
					"productName": "AV88CB Орасі баріста кокос, напій кокосовий з рисом 6х1л",
					"amount": 3,
					"storeName": "Склад №1",
					"unitWeight": 6.0,
					"totalProductWeight": 18.0
				},
				{
					"productName": "AV88AB Орасі баріста соя, соєвий напій 6х1л. (нова)",
					"amount": 2,
					"storeName": "Склад №1",
					"unitWeight": 6.0,
					"totalProductWeight": 12.0
				}
			],
			"orderWeight": 72.0,
			"validAddress": false
		},
		{
			"id": 0,
			"refKey": "050e5ea7-8fd4-11ec-b3ce-00155dd72305",
			"orderNumber": "00000003830",
			"createdDate": "2022-02-17",
			"clientName": "Домашня випічка",
			"address": "Бровари, Марії Лагунової, 11, тел.050-380-08-29",
			"comment": "нал, тел. 050-380-08-29",
			"managerFullName": "Балашова Лариса                                   ",
			"products": [
				{
					"productName": "Крем заварний Фортуна (10 кг)",
					"amount": 7,
					"storeName": "Склад №1",
					"unitWeight": 10.0,
					"totalProductWeight": 70.0
				},
				{
					"productName": "Порошок до печива ЛЮКС  (5 кг)",
					"amount": 1,
					"storeName": "Склад №1",
					"unitWeight": 5.0,
					"totalProductWeight": 5.0
				}
			],
			"orderWeight": 75.0,
			"validAddress": false
		}
	],
	"totalOrdersWeight": 298.0
}
